--- 
title: "Notes"
author: "Joyce Robbins"
date: "`r Sys.Date()`"
description: "Random notes about bookdown and other stuff."

---

# rmarkdown

## Tables

### Adjust column width with knitr::kable()

`html_table_width()` function:

```{r, eval=FALSE}
html_table_width <- function(kable_output, width){
  width_html <- paste0(paste0('<col width="', width, '">'), collapse = "\n")
  sub("<table>", paste0("<table>\n", width_html), kable_output)
}
```

[https://github.com/rstudio/bookdown/issues/122](https://github.com/rstudio/bookdown/issues/122){target="_blank"}

### Line breaks in table cells with knitr::kable()

*best option*

add `<br>`


```{r}
x <- data.frame(a = "asdf asdf", b = "asdf<br>asdf")
knitr::kable(x)
```


### Line breaks in table cells with knitr::kable(), using `format="html"`

Add `escape=FALSE`

```{r}
x <- data.frame(a = "asdf asdf", b = "asdf<br>asdf")
knitr::kable(x, format="html", escape=FALSE)
```


## Verbatim code chunks

https://rmarkdown.rstudio.com/articles_verbatim.html

Why it works:

https://yihui.name/en/2017/11/knitr-verbatim-code-chunk/


